### ISSUE TITLE
Fetching dependencies fails with Python exception

### ISSUE THREAD

**Issue by the42** [heroku/heroku-buildpack-go#45]
When pushing a new version of my Go app to Heroku, the process fails with:

cd .; hg clone -U https://code.google.com/p/go-uuid /tmp/build_3bf11f97-2087-47a6-a45f-119ef80e1247/.heroku/g/src/code.google.com/p/go-uuid
Traceback (most recent call last):
  File "/app/tmp/cache/venv/bin/hg", line 36, in <module>
    mercurial.util.setbinary(fp)
  File "/app/tmp/cache/venv/lib/python2.7/site-packages/mercurial/demandimport.py", line 102, in __getattribute__
    self._load()
  File "/app/tmp/cache/venv/lib/python2.7/site-packages/mercurial/demandimport.py", line 74, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/app/tmp/cache/venv/lib/python2.7/site-packages/mercurial/demandimport.py", line 43, in _hgextimport
    return importfunc(name, globals, *args)
  File "/app/tmp/cache/venv/lib/python2.7/site-packages/mercurial/util.py", line 16, in <module>
    from i18n import _
  File "/app/tmp/cache/venv/lib/python2.7/site-packages/mercurial/demandimport.py", line 130, in _demandimport
    mod = _hgextimport(_origimport, name, globals, locals)
  File "/app/tmp/cache/venv/lib/python2.7/site-packages/mercurial/demandimport.py", line 43, in _hgextimport
    return importfunc(name, globals, *args)
  File "/app/tmp/cache/venv/lib/python2.7/site-packages/mercurial/i18n.py", line 23, in <module>
    t = gettext.translation('hg', localedir, fallback=True)
  File "/usr/local/lib/python2.7/gettext.py", line 465, in translation
    mofiles = find(domain, localedir, languages, all=1)
  File "/usr/local/lib/python2.7/gettext.py", line 437, in find
    for nelang in _expand_lang(lang):
  File "/usr/local/lib/python2.7/gettext.py", line 131, in _expand_lang
    from locale import normalize
  File "/app/tmp/cache/venv/lib/python2.7/site-packages/mercurial/demandimport.py", line 111, in _demandimport
    return _hgextimport(_import, name, globals, locals, fromlist, level)
  File "/app/tmp/cache/venv/lib/python2.7/site-packages/mercurial/demandimport.py", line 43, in _hgextimport
    return importfunc(name, globals, *args)
  File "/app/tmp/cache/venv/lib/python2.7/locale.py", line 182, in <module>
    _percent_re = re.compile(r'%(?:\((?P<key>.*?)\))?'
  File "/app/tmp/cache/venv/lib/python2.7/site-packages/mercurial/demandimport.py", line 102, in __getattribute__
    self._load()
  File "/app/tmp/cache/venv/lib/python2.7/site-packages/mercurial/demandimport.py", line 74, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/app/tmp/cache/venv/lib/python2.7/site-packages/mercurial/demandimport.py", line 43, in _hgextimport
    return importfunc(name, globals, *args)
  File "/app/tmp/cache/venv/lib/python2.7/re.py", line 222, in <module>
    _pattern_type = type(sre_compile.compile("", 0))
  File "/app/tmp/cache/venv/lib/python2.7/sre_compile.py", line 502, in compile
    code = _code(p, flags)
  File "/app/tmp/cache/venv/lib/python2.7/sre_compile.py", line 484, in _code
    _compile_info(code, p, flags)
  File "/app/tmp/cache/venv/lib/python2.7/sre_compile.py", line 363, in _compile_info
    lo, hi = pattern.getwidth()
  File "/app/tmp/cache/venv/lib/python2.7/sre_parse.py", line 174, in getwidth
    self.width = min(lo, MAXREPEAT - 1), min(hi, MAXREPEAT)
TypeError: unsupported operand type(s) for -: '_demandmod' and 'int'

Seems like an incompatible Python version?

**Comment by freeformz** [comment]
I'm going to close this for now as I cannot duplicate.

Please re-open if this is still an issue.

Thanks!
